"""correction table livre

Revision ID: 06d4ff5f0805
Revises: 
Create Date: 2026-09-20 13:45:04.781209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d4ff5f0805'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livres',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('auteur', sa.String(length=100), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('date_publication', sa.Date(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('disponibles', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_livres_auteur'), 'livres', ['auteur'], unique=False)
    op.create_index(op.f('ix_livres_genre'), 'livres', ['genre'], unique=False)
    op.create_index(op.f('ix_livres_titre'), 'livres', ['titre'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('mdp', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('emprunts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['livres.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emprunts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_livres_titre'), table_name='livres')
    op.drop_index(op.f('ix_livres_genre'), table_name='livres')
    op.drop_index(op.f('ix_livres_auteur'), table_name='livres')
    op.drop_table('livres')
    # ### end Alembic commands ###
