"""empty message

Revision ID: b62309f18529
Revises: e297dd5b1bcc
Create Date: 2026-09-21 13:39:44.960277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b62309f18529'
down_revision: Union[str, Sequence[str], None] = 'e297dd5b1bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emprunts', sa.Column('rendu', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emprunts', 'rendu')
    # ### end Alembic commands ###
