"""empty message

Revision ID: e996dc0ce5aa
Revises: d78184b45014
Create Date: 2026-09-18 14:46:47.637242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e996dc0ce5aa'
down_revision: Union[str, Sequence[str], None] = 'd78184b45014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mdp', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mdp')
    # ### end Alembic commands ###
